import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  index,
  integer,
  numeric,
  pgTable,
  text,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import { baseColumns, MONEY } from "./_shared";
import { invoiceStatusEnum, receiptModeEnum } from "./enums";
import { dispatchLine } from "./dispatch";
import { client } from "./reference";

/* -------------------------------------------------------------------------- */
/* invoice                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Busy is the book of record for accounts. This system does NOT calculate GST
 * (decision D) — the tax amounts are typed in to match what Busy produced, and
 * invoice_no is the number Busy raised, not one we allocate.
 *
 * The purpose of holding invoices here at all is to answer "what is
 * outstanding from X" without opening Busy, and to tie revenue back to the
 * dispatch lines that earned it.
 */
export const invoice = pgTable(
  "invoice",
  {
    ...baseColumns(),

    /** Matches the number raised in Busy. Not generated by this system. */
    invoiceNo: text().notNull(),

    clientId: uuid()
      .notNull()
      .references(() => client.id),

    invoiceDate: date().notNull(),

    /** invoice_date + client.payment_terms_days, at time of raising. */
    dueDate: date(),

    taxableAmount: numeric(MONEY).notNull().default("0"),
    cgst: numeric(MONEY).notNull().default("0"),
    sgst: numeric(MONEY).notNull().default("0"),
    igst: numeric(MONEY).notNull().default("0"),
    totalAmount: numeric(MONEY).notNull().default("0"),

    /** Derived from allocations; see v_ar_ageing. */
    status: invoiceStatusEnum().notNull().default("Draft"),

    /** Manual tick — a reconciliation aid, not an integration. */
    busySynced: boolean().notNull().default(false),

    notes: text(),
  },
  (t) => [
    uniqueIndex("invoice_no_key")
      .on(t.invoiceNo)
      .where(sql`${t.deletedAt} is null`),
    index("invoice_client_idx").on(t.clientId),
    index("invoice_date_idx").on(t.invoiceDate),
    index("invoice_due_date_idx").on(t.dueDate),
    index("invoice_status_idx").on(t.status),

    check("invoice_total_non_negative", sql`${t.totalAmount} >= 0`),
  ],
);

/* -------------------------------------------------------------------------- */
/* invoice_line                                                                */
/* -------------------------------------------------------------------------- */

/**
 * Each line references the dispatch_line it bills, which is what lets the
 * Invoicing screen show "dispatch lines not yet invoiced" and prevents the
 * same delivery being billed twice.
 *
 * A trigger enforces that the referenced dispatch line belongs to the same
 * client as the invoice (decision C8).
 */
export const invoiceLine = pgTable(
  "invoice_line",
  {
    ...baseColumns(),

    invoiceId: uuid()
      .notNull()
      .references(() => invoice.id, { onDelete: "cascade" }),

    dispatchLineId: uuid()
      .notNull()
      .references(() => dispatchLine.id),

    description: text(),
    qty: integer().notNull(),
    rate: numeric(MONEY),
    amount: numeric(MONEY).notNull().default("0"),
  },
  (t) => [
    index("invoice_line_invoice_idx").on(t.invoiceId),
    uniqueIndex("invoice_line_dispatch_line_key")
      .on(t.dispatchLineId)
      .where(sql`${t.deletedAt} is null`),
    check("invoice_line_qty_positive", sql`${t.qty} > 0`),
  ],
);

/* -------------------------------------------------------------------------- */
/* receipt                                                                     */
/* -------------------------------------------------------------------------- */

export const receipt = pgTable(
  "receipt",
  {
    ...baseColumns(),

    /** RCP-YYYY-NNNN, financial year. */
    receiptNo: text().notNull(),

    clientId: uuid()
      .notNull()
      .references(() => client.id),

    receiptDate: date().notNull(),
    amount: numeric(MONEY).notNull(),

    mode: receiptModeEnum().notNull().default("NEFT"),
    referenceNo: text(),
    notes: text(),
  },
  (t) => [
    uniqueIndex("receipt_no_key")
      .on(t.receiptNo)
      .where(sql`${t.deletedAt} is null`),
    index("receipt_client_idx").on(t.clientId),
    index("receipt_date_idx").on(t.receiptDate),
    check("receipt_amount_positive", sql`${t.amount} > 0`),
  ],
);

/* -------------------------------------------------------------------------- */
/* receipt_allocation                                                          */
/* -------------------------------------------------------------------------- */

/**
 * One payment routinely settles several invoices, and sometimes leaves a
 * remainder sitting as on-account credit. That is why allocation is its own
 * table rather than a receipt.invoice_id column.
 *
 * Triggers enforce both spec constraints, since each needs to see sibling
 * rows and so cannot be a CHECK:
 *   SUM(amount) per receipt <= receipt.amount   (remainder = on-account)
 *   SUM(amount) per invoice <= invoice.total_amount
 */
export const receiptAllocation = pgTable(
  "receipt_allocation",
  {
    ...baseColumns(),

    receiptId: uuid()
      .notNull()
      .references(() => receipt.id, { onDelete: "cascade" }),

    invoiceId: uuid()
      .notNull()
      .references(() => invoice.id),

    amount: numeric(MONEY).notNull(),
  },
  (t) => [
    index("receipt_allocation_receipt_idx").on(t.receiptId),
    index("receipt_allocation_invoice_idx").on(t.invoiceId),
    check("receipt_allocation_amount_positive", sql`${t.amount} > 0`),
  ],
);

export type Invoice = typeof invoice.$inferSelect;
export type InvoiceLine = typeof invoiceLine.$inferSelect;
export type Receipt = typeof receipt.$inferSelect;
export type ReceiptAllocation = typeof receiptAllocation.$inferSelect;
