-- ===========================================================================
-- Generated by drizzle-kit, then extended with the data statement below.
--
-- stage.is_process — decision F18.
--
-- Separates the stages a job physically passes through on the floor from the
-- ones that are points in the order's lifecycle. Both are real stage events;
-- only the first kind belongs on a DESIGN's route, which describes how a job is
-- manufactured rather than where an order has got to.
--
-- This filters the design route editor and nothing else. Stage Update offers
-- every stage regardless — Preeti has to be able to move a job to READY and
-- DISPATCHED, and those are not route steps.
--
-- The column defaults TRUE, so the UPDATE below only has to name the six
-- lifecycle stages. Both halves ship together: shipping the column without the
-- values would leave ENQUIRY and COSTING offered as manufacturing steps, which
-- is the state F18 exists to fix.
--
-- The values are seeded here rather than left to the Admin screen because they
-- are the current vocabulary, not a preference — but they stay editable there,
-- so the vocabulary can change without another migration.
-- ===========================================================================

ALTER TABLE "stage" ADD COLUMN "is_process" boolean DEFAULT true NOT NULL;
--> statement-breakpoint

-- Order lifecycle, not floor work. Everything else keeps the TRUE default:
-- DESIGN, MATERIAL_READY, PRINTING, LAMINATION, UV, FOILING, DIE_CUT, PASTING.
UPDATE stage
SET is_process = false
WHERE code IN ('ENQUIRY', 'COSTING', 'PO_RECEIVED', 'APPROVED', 'READY', 'DISPATCHED');
