-- ===========================================================================
-- Generated by drizzle-kit, then annotated. The statements are the generated
-- ones.
--
-- import_batch, and the import_batch_id that four tables now carry.
--
-- The batch exists so a bad import can be identified and reversed. Without it,
-- forty jobs entered from a mistyped spreadsheet would have to be unpicked from
-- the audit log by hand, working out which rows came from the file and which
-- somebody typed the same afternoon.
--
-- The created rows point BACK at the batch rather than the batch holding a list
-- of them. A foreign key stays true; a list of ids in a column does not.
--
-- UNDO IS A SOFT DELETE and cannot be anything else. stage_event is
-- append-only, enforced by a trigger from migration 0001, so the PO_RECEIVED
-- and DISPATCHED events a batch wrote cannot be removed. Soft-deleting the
-- po_item rows takes them out of v_po_item_status and every view built on it,
-- leaving those events attached to rows nothing displays — which is the right
-- outcome rather than a workaround. What was entered and then withdrawn is
-- exactly what an audit trail is for.
-- ===========================================================================

CREATE TABLE "import_batch" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"deleted_at" timestamp with time zone,
	"filename" text NOT NULL,
	"row_count" integer DEFAULT 0 NOT NULL,
	"imported_count" integer DEFAULT 0 NOT NULL,
	"skipped_count" integer DEFAULT 0 NOT NULL,
	"imported_by" uuid NOT NULL,
	"undone_at" timestamp with time zone,
	"undone_by" uuid
);
--> statement-breakpoint
ALTER TABLE "po_item" ADD COLUMN "import_batch_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_order" ADD COLUMN "import_batch_id" uuid;--> statement-breakpoint
ALTER TABLE "dispatch" ADD COLUMN "import_batch_id" uuid;--> statement-breakpoint
ALTER TABLE "dispatch_line" ADD COLUMN "import_batch_id" uuid;--> statement-breakpoint
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_imported_by_app_user_id_fk" FOREIGN KEY ("imported_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "import_batch" ADD CONSTRAINT "import_batch_undone_by_app_user_id_fk" FOREIGN KEY ("undone_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "import_batch_imported_by_idx" ON "import_batch" USING btree ("imported_by");--> statement-breakpoint
CREATE INDEX "import_batch_created_at_idx" ON "import_batch" USING btree (created_at desc);--> statement-breakpoint
ALTER TABLE "po_item" ADD CONSTRAINT "po_item_import_batch_id_import_batch_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_order" ADD CONSTRAINT "purchase_order_import_batch_id_import_batch_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch" ADD CONSTRAINT "dispatch_import_batch_id_import_batch_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dispatch_line" ADD CONSTRAINT "dispatch_line_import_batch_id_import_batch_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batch"("id") ON DELETE no action ON UPDATE no action;
