-- ===========================================================================
-- Generated by drizzle-kit, then annotated. The statements are the generated
-- ones.
--
-- The importer may now CREATE a client (decision F32), where it used to refuse
-- every name it did not already recognise. Three columns record that, and each
-- one is load-bearing:
--
--   import_batch_id     which import invented this client. It is what puts the
--                       client inside that batch's undo — reversing an import
--                       removes the customers it conjured, and leaves alone the
--                       ones it merely matched against, which carry null here.
--                       Without it, auto-creation would be a one-way door.
--
--   import_reviewed_at  whether a human has since looked at it. An auto-created
--   import_reviewed_by  client has a generated code, no GSTIN and no address:
--                       it is a record waiting to be finished, not a finished
--                       one. Null here alongside a non-null batch id is exactly
--                       what the "created by import, unreviewed" filter on the
--                       client list selects.
--
-- Nothing is backfilled. Every client that exists today was typed by a person,
-- so a null batch id is the truth for all of them.
-- ===========================================================================

ALTER TABLE "client" ADD COLUMN "import_batch_id" uuid;--> statement-breakpoint
ALTER TABLE "client" ADD COLUMN "import_reviewed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "client" ADD COLUMN "import_reviewed_by" uuid;--> statement-breakpoint
ALTER TABLE "client" ADD CONSTRAINT "client_import_batch_id_import_batch_id_fk" FOREIGN KEY ("import_batch_id") REFERENCES "public"."import_batch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client" ADD CONSTRAINT "client_import_reviewed_by_app_user_id_fk" FOREIGN KEY ("import_reviewed_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "client_import_batch_idx" ON "client" USING btree ("import_batch_id");