-- ===========================================================================
-- Generated by drizzle-kit, then annotated. The statements are the generated
-- ones.
--
-- delegation_task — the BMP week 9 accountability layer. ONE-TIME tasks with a
-- date, a person, and a score that gets read aloud in the executive meeting.
--
-- THERE IS DELIBERATELY NO RECURRENCE COLUMN (decision G5). Recurring work
-- belongs on a checklist. A repeating task here either scores once, making the
-- repetition pointless, or scores every occurrence and drowns genuine one-time
-- commitments under routine ticks.
--
-- FOUR CHECK CONSTRAINTS, and they are in the database rather than only in a
-- server action for the reason F11 gives: a rule that lives only in TypeScript
-- is a rule a psql session does not have.
--
--   done_needs_completed_at    Done with no date has nothing for days_late to
--                              measure, so the task finishes at no cost.
--   blocked_needs_note         "Blocked" with no note reads as a reason and
--                              carries no information.
--   completed_at_only_when_done  v_delegation_status reads completed_at FIRST.
--                              A date left behind on a task moved back to In
--                              Progress would freeze its lateness at the old
--                              value — a wrong score with no error.
--   expected_after_given       A task cannot be due before it was given.
--
-- date_given defaults to today_ist(), not now()::date. C10: every date boundary
-- in this system is Asia/Kolkata, and a task delegated at 9am IST on the 3rd is
-- 03:30 UTC — same day — while one at 2am IST is the previous day in UTC.
-- ===========================================================================

CREATE TYPE "public"."delegation_level" AS ENUM('L2', 'L3', 'L4');--> statement-breakpoint
CREATE TYPE "public"."delegation_status" AS ENUM('Not Started', 'In Progress', 'Done', 'Blocked', 'Cancelled');--> statement-breakpoint
CREATE TABLE "delegation_task" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"deleted_at" timestamp with time zone,
	"assigned_to" uuid NOT NULL,
	"assigned_by" uuid NOT NULL,
	"task" text NOT NULL,
	"level" "delegation_level" DEFAULT 'L2' NOT NULL,
	"date_given" date DEFAULT today_ist() NOT NULL,
	"expected_date" date NOT NULL,
	"status" "delegation_status" DEFAULT 'Not Started' NOT NULL,
	"completed_at" date,
	"blocker_note" text,
	CONSTRAINT "delegation_done_needs_completed_at" CHECK ("delegation_task"."status" <> 'Done' OR "delegation_task"."completed_at" IS NOT NULL),
	CONSTRAINT "delegation_blocked_needs_note" CHECK ("delegation_task"."status" <> 'Blocked' OR ("delegation_task"."blocker_note" IS NOT NULL AND length(trim("delegation_task"."blocker_note")) > 0)),
	CONSTRAINT "delegation_completed_at_only_when_done" CHECK ("delegation_task"."completed_at" IS NULL OR "delegation_task"."status" = 'Done'),
	CONSTRAINT "delegation_expected_after_given" CHECK ("delegation_task"."expected_date" >= "delegation_task"."date_given")
);
--> statement-breakpoint
ALTER TABLE "delegation_task" ADD CONSTRAINT "delegation_task_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delegation_task" ADD CONSTRAINT "delegation_task_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delegation_task" ADD CONSTRAINT "delegation_task_assigned_to_app_user_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "delegation_task" ADD CONSTRAINT "delegation_task_assigned_by_app_user_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "delegation_task_assigned_to_idx" ON "delegation_task" USING btree ("assigned_to");--> statement-breakpoint
CREATE INDEX "delegation_task_assigned_by_idx" ON "delegation_task" USING btree ("assigned_by");--> statement-breakpoint
CREATE INDEX "delegation_task_expected_date_idx" ON "delegation_task" USING btree ("expected_date");--> statement-breakpoint
CREATE INDEX "delegation_task_status_idx" ON "delegation_task" USING btree ("status");