-- ===========================================================================
-- Generated by drizzle-kit, then annotated. The statements are the generated
-- ones.
--
-- press_run — GANGING. Three to eight times a month, items from DIFFERENT
-- clients are printed together on one plate to fill a sheet. The system could
-- not represent that at all, so the Item Tracker implied every job ran
-- standalone, which was false about one job in twenty.
--
-- THIS SITS ABOVE JOB CARDS, NOT BELOW THEM. job_card.po_item_id is untouched
-- and still NOT NULL: one job card is still exactly one PO item. Ganging adds
-- that several job cards may share a press run. Spec section 3's "no ganging
-- across clients in v1" is superseded; "one job card = one PO item" is not.
-- See decision H1.
--
-- press_run_id IS NULLABLE ON PURPOSE. The overwhelming majority of job cards
-- are not ganged and must stay exactly as they are — a null means "printed on
-- its own", which is both the common case and the truth about every row that
-- already exists. Nothing is backfilled.
--
-- NO CLIENT COLUMN AND NO CROSS-CLIENT CONSTRAINT, deliberately. The triggers
-- in migration 0001 that refuse a mixed-client dispatch or invoice (C8) do NOT
-- extend here: on a challan a second client is a mistake, on a plate it is the
-- entire reason the plate exists. Adding a guard here for consistency with
-- those would break the feature (H3).
--
-- No status column either (H5). A press run is a thing that happened on a date,
-- not a thing that is open or closed, and "open runs" on the add-to-run picker
-- means recent ones.
-- ===========================================================================

CREATE TABLE "press_run" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"deleted_at" timestamp with time zone,
	"run_no" text NOT NULL,
	"run_date" date NOT NULL,
	"machine" text,
	"notes" text
);
--> statement-breakpoint
ALTER TABLE "job_card" ADD COLUMN "press_run_id" uuid;--> statement-breakpoint
ALTER TABLE "press_run" ADD CONSTRAINT "press_run_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "press_run" ADD CONSTRAINT "press_run_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "press_run_no_key" ON "press_run" USING btree ("run_no") WHERE "press_run"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "press_run_date_idx" ON "press_run" USING btree ("run_date");--> statement-breakpoint
ALTER TABLE "job_card" ADD CONSTRAINT "job_card_press_run_id_press_run_id_fk" FOREIGN KEY ("press_run_id") REFERENCES "public"."press_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "job_card_press_run_idx" ON "job_card" USING btree ("press_run_id");