-- ===========================================================================
-- Generated by drizzle-kit, then annotated. The statements are the generated
-- ones.
--
-- tooling — the physical plates, foil blocks, dies and embossing blocks the
-- factory owns.
--
-- ONE TABLE WITH A TYPE DISCRIMINATOR, not four near-identical ones (I1).
-- Every question anybody asks of tooling is the same for all four kinds:
-- where is it, what condition, whose job, what replaced it. Four tables would
-- mean four screens and four places to forget a filter, and "everything in
-- rack 3" would need a union.
--
-- THE COLUMN THIS TABLE EXISTS FOR IS location, which is why it is NOT NULL
-- and why there is an index on it. The register is read far more often to
-- answer "where is the die for X" than for anything else.
--
-- replaces_tool_id is a SELF reference, pointing BACK at what a tool
-- superseded, so the chain reads newest-first and adding a replacement never
-- edits the row being replaced. A CHECK stops a row replacing itself.
--
-- THIS MIGRATION IS STEP 1 OF THREE. It only creates the table. The design
-- table still holds die_id, plate_id, die_status and plate_status at this
-- point, which means two sources of truth for the same question — deliberately
-- and briefly:
--
--   0014 (this)  create tooling
--   script       npm run migrate:tooling            (dry run, then --apply)
--   0016         drop the four design columns
--
-- Migration 0016 REFUSES TO RUN until the script has been applied, so the
-- ordering cannot be got wrong by running db:migrate. See its header.
-- ===========================================================================

CREATE TYPE "public"."tool_condition" AS ENUM('Good', 'Worn', 'Damaged', 'Scrapped');--> statement-breakpoint
CREATE TYPE "public"."tool_status" AS ENUM('In House', 'With Vendor', 'Issued to Floor', 'Lost');--> statement-breakpoint
CREATE TYPE "public"."tool_type" AS ENUM('PLATE', 'FOIL_BLOCK', 'DIE', 'EMBOSS_BLOCK');--> statement-breakpoint
CREATE TABLE "tooling" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_by" uuid,
	"deleted_at" timestamp with time zone,
	"tool_no" text NOT NULL,
	"tool_type" "tool_type" NOT NULL,
	"design_id" uuid,
	"client_id" uuid,
	"name" text NOT NULL,
	"size" text,
	"colour" text,
	"location" text NOT NULL,
	"condition" "tool_condition" DEFAULT 'Good' NOT NULL,
	"status" "tool_status" DEFAULT 'In House' NOT NULL,
	"made_date" date,
	"vendor" text,
	"cost" numeric(14, 2),
	"impressions_used" integer,
	"last_used_date" date,
	"replaces_tool_id" uuid,
	"remarks" text,
	CONSTRAINT "tooling_not_self_replacing" CHECK ("tooling"."replaces_tool_id" is null or "tooling"."replaces_tool_id" <> "tooling"."id"),
	CONSTRAINT "tooling_impressions_non_negative" CHECK ("tooling"."impressions_used" is null or "tooling"."impressions_used" >= 0),
	CONSTRAINT "tooling_cost_non_negative" CHECK ("tooling"."cost" is null or "tooling"."cost" >= 0),
	CONSTRAINT "tooling_location_not_blank" CHECK (length(trim("tooling"."location")) > 0),
	CONSTRAINT "tooling_name_not_blank" CHECK (length(trim("tooling"."name")) > 0)
);
--> statement-breakpoint
ALTER TABLE "tooling" ADD CONSTRAINT "tooling_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tooling" ADD CONSTRAINT "tooling_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tooling" ADD CONSTRAINT "tooling_design_id_design_id_fk" FOREIGN KEY ("design_id") REFERENCES "public"."design"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tooling" ADD CONSTRAINT "tooling_client_id_client_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."client"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tooling" ADD CONSTRAINT "tooling_replaces_tool_id_tooling_id_fk" FOREIGN KEY ("replaces_tool_id") REFERENCES "public"."tooling"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "tooling_no_key" ON "tooling" USING btree ("tool_no") WHERE "tooling"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "tooling_type_idx" ON "tooling" USING btree ("tool_type");--> statement-breakpoint
CREATE INDEX "tooling_design_idx" ON "tooling" USING btree ("design_id");--> statement-breakpoint
CREATE INDEX "tooling_client_idx" ON "tooling" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "tooling_status_idx" ON "tooling" USING btree ("status");--> statement-breakpoint
CREATE INDEX "tooling_condition_idx" ON "tooling" USING btree ("condition");--> statement-breakpoint
CREATE INDEX "tooling_replaces_idx" ON "tooling" USING btree ("replaces_tool_id");--> statement-breakpoint
CREATE INDEX "tooling_location_idx" ON "tooling" USING btree ("location");