-- ===========================================================================
-- Generated by drizzle-kit, then given a guard by hand.
-- The ALTER statements are the generated ones; the DO block is not.
--
-- Drops design.die_id, plate_id, die_status and plate_status.
--
-- Until now these were free text holding the same facts the tooling register
-- now holds properly, which is TWO SOURCES OF TRUTH for "does this design have
-- a die, and where is it". One of them was always going to be wrong, and the
-- wrong one would have been whichever nobody updated that week.
--
-- ###########################################################################
-- #                                                                         #
-- #  THIS MIGRATION GUARDS ITSELF AND WILL REFUSE TO RUN EARLY.             #
-- #                                                                         #
-- #  drizzle applies migrations in order, automatically. Without the check   #
-- #  below, a plain `npm run db:migrate` on a database that had not yet run  #
-- #  scripts/migrate-tooling.ts would drop the only copy of that data — no   #
-- #  error, no warning, nothing to restore from. The check turns a silent    #
-- #  data-loss footgun into a stop with instructions.                        #
-- #                                                                         #
-- ###########################################################################
--
-- The rule it enforces: no LIVE design may still hold a die or plate value
-- while having no tooling row against it. That is exactly the condition the
-- script clears, so the guard passes the moment the script has run and not a
-- moment before.
--
-- Placeholder values ('-', 'NA', 'nil' and friends) are treated as empty here
-- in the same way the script's planner treats them, or a design whose die_id
-- says "NA" would block the drop forever over data nobody wants migrated.
--
-- Sequence (decision I7):
--   0014, 0015   create tooling and its client-derivation trigger
--   script       npm run migrate:tooling            (dry run, then --apply)
--   0016 (this)  drop the four columns
-- ===========================================================================

DO $$
DECLARE
  unmigrated integer;
BEGIN
  SELECT count(*) INTO unmigrated
  FROM design d
  WHERE d.deleted_at IS NULL
    AND (
      lower(coalesce(btrim(d.die_id), '')) NOT IN ('', '-', '--', 'n/a', 'na', 'nil', 'none', 'no', 'x')
      OR
      lower(coalesce(btrim(d.plate_id), '')) NOT IN ('', '-', '--', 'n/a', 'na', 'nil', 'none', 'no', 'x')
    )
    AND NOT EXISTS (
      SELECT 1 FROM tooling t
      WHERE t.design_id = d.id AND t.deleted_at IS NULL
    );

  IF unmigrated > 0 THEN
    RAISE EXCEPTION
      'Refusing to drop design.die_id/plate_id: % design(s) still hold tooling data that is not in the tooling register. Run "npm run migrate:tooling" to see what would move, then "npm run migrate:tooling -- --apply", then run this migration again.',
      unmigrated;
  END IF;
END $$;
--> statement-breakpoint

ALTER TABLE "design" DROP COLUMN "die_id";--> statement-breakpoint
ALTER TABLE "design" DROP COLUMN "plate_id";--> statement-breakpoint
ALTER TABLE "design" DROP COLUMN "die_status";--> statement-breakpoint
ALTER TABLE "design" DROP COLUMN "plate_status";